version: '3.7'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    env_file:
      - .env
  web:
    image: flowhack/whoisjerk_tbot
    restart: always
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: